动物级别:
  普通:
    生物ID:
      - Crocodile
      - Bison
    价值: 100
  少见:
    生物ID:
      - Kangaroo
    价值: 250
  珍稀:
    生物ID:
      - Bald Eagle
    价值: 500
  史诗:
    生物ID:
      - Tiger
    价值: 800
  传奇:
    生物ID:
      - Elephant
    价值: 1200
  神话:
    生物ID:
      - Caiman
    价值: 1800